"""Shared pytest fixtures for pyworkflow's own test suite.

These wrap the same free functions BaseTest (pyworkflow/tests/tests.py) uses
internally (setupTestProject/setupTestOutput), so BaseTest itself stays
untouched and keeps working for scipion-em and other downstream consumers.
"""
import logging
import os

import pytest

import pyworkflow as pw
from pyworkflow.protocol import getProtocolFromDb
from pyworkflow.tests.tests import setupTestOutput, setupTestProject

logger = logging.getLogger(__name__)

os.makedirs(os.path.join(pw.Config.SCIPION_HOME, "config"), exist_ok=True)


class _Namespace:
    """Stand-in for the `cls` argument setupTestProject/setupTestOutput
    expect - they only ever set attributes on it and read `__name__`."""


def _projectNameFor(request) -> str:
    # Sanitize so parametrized test ids (which contain [] and other
    # punctuation) are still valid project/directory names.
    return "".join(c if c.isalnum() else "_" for c in request.node.name)


@pytest.fixture
def testProject(request):
    """Creates a real Scipion Project (SQLite-backed) for a single test,
    mirroring what BaseTest.setUpClass used to set up once per test class.
    """
    ns = _Namespace()
    ns.__name__ = _projectNameFor(request)
    setupTestProject(ns, writeLocalConfig=True)
    yield ns.proj
    ns.proj.closeMapper()


@pytest.fixture
def testOutputPath(request):
    """Creates (and cleans) the output folder for a single test."""
    ns = _Namespace()
    ns.__name__ = _projectNameFor(request)
    setupTestOutput(ns)
    return ns.outputPath


def launchProtocol(project, prot, wait=None, waitForOutput=()):
    """Launch a protocol through `project` and wait for it to finish (or,
    if `waitForOutput` is given and `wait` isn't forced True, poll until
    those output attributes appear). Raises on failure/non-completion.
    """
    if wait is None:
        wait = not waitForOutput

    if getattr(prot, "_run", True):
        project.launchProtocol(prot, wait=wait)
        if not wait and waitForOutput:
            import time
            while True:
                time.sleep(10)
                prot = project._updateProtocol(prot)
                if all(prot.hasAttribute(o) for o in waitForOutput):
                    break

    if prot.isFailed():
        printLastLogLines(prot)
        raise Exception(
            "Protocol %s execution failed. See last log lines above for more details."
            % prot.getRunName()
        )

    if not prot.isFinished() and not prot.useQueue():
        printLastLogLines(prot)
        raise Exception(
            "Protocol %s didn't finish. See last log lines above for more details."
            % prot.getRunName()
        )

    return prot


def printLastLogLines(prot):
    lastLines = int(os.environ.get("PROT_LOGS_LAST_LINES", 50))
    for label, logFile in (("STD OUT", 0), ("STD ERR", 1)):
        logger.info("\n*************** last %s lines of %s *********************\n", lastLines, label)
        for line in prot.getLogsLastLines(lastLines, logFile=logFile):
            logger.info(line)
        logger.info("\n*************** end of %s *********************\n", label)


def waitOutput(project, prot, outputAttributeName, sleepTime=20, timeOut=5000):
    """Wait until `outputAttributeName` is generated by `prot`."""
    import time

    def _loadProt():
        loadedProt = getProtocolFromDb(prot.getProject().path, prot.getDbPath(), prot.getObjId())
        loadedProt.getProject().closeMapper()
        loadedProt.closeMappers()
        return loadedProt

    counter = 1
    prot2 = _loadProt()
    numberOfSleeps = timeOut / sleepTime

    while (not prot2.hasAttribute(outputAttributeName)) and prot2.isActive():
        time.sleep(sleepTime)
        prot2 = _loadProt()
        if counter > numberOfSleeps:
            logger.warning("Timeout (%s) reached waiting for %s at %s", timeOut, outputAttributeName, prot)
            break
        counter += 1

    project._updateProtocol(prot)


def compareSets(set1, set2):
    """Assert that both sets' elements have equal attributes, pairwise."""
    for item1, item2 in zip(set1, set2):
        areEqual = item1.equalAttributes(item2)
        if not areEqual:
            logger.info("item 1 and item2 are different: ")
            item1.printAll()
            item2.printAll()
        assert areEqual


def compareSetProperties(set1, set2, ignore=("_size", "_mapperPath")):
    assert set1.equalAttributes(set2, ignore=ignore, verbose=True), (
        f"Set1 ({set1}) properties differ from set2 ({set2})."
    )
    assert set2.equalAttributes(set1, ignore=ignore, verbose=True), (
        f"Set2 ({set2}) has properties that set1 ({set1}) does not have."
    )


def assertIsNotEmpty(setObject):
    assert setObject is not None
    assert setObject.get() is not None


def assertSetSize(setObject, size=None, diffDelta=None):
    assert setObject is not None
    setObjSize = setObject.getSize()
    if size is None:
        assert setObjSize != 0
    elif diffDelta:
        assert abs(setObjSize - size) <= round(diffDelta * size)
    else:
        assert setObjSize == size
